name: Configure kubecontext
description: Configure kubecontext for environment specific deployment

inputs:
  k8s_cluster_name:
    required: true
    description: "Kubernetes Cluster Name"
  k8s_cert:
    required: true
    description: "Kubernetes Cluster Certificate"
  k8s_namespace:
    required: true
    description: "Kubernetes Namespace"
  k8s_token:
    required: true
    description: "Kubernetes API Token"
  k8s_service_account:
    required: true
    description: "Kubernetes Service Account"

runs:
  using: "composite"

  steps:
  - name: Kubernetes Auth
    run: |
      kubectl config set-cluster ${{ inputs.k8s_cluster_name }} --server="https://${{ inputs.k8s_cluster_name }}"
      kubectl config set-credentials ${{ inputs.k8s_service_account }} --token=${{ inputs.k8s_token }}
    shell: bash

  - name: Configure kubecontext
    run: |  
      kubectl config set-context ${{ inputs.k8s_cluster_name }} --cluster=${{ inputs.k8s_cluster_name }} --user=${{ inputs.k8s_service_account }} --namespace=${{ inputs.k8s_namespace }}
      kubectl config use-context ${{ inputs.k8s_cluster_name }}
    shell: bash
