apiVersion: v1
kind: Pod
metadata:
  name: cwa-test-controller-pod
spec:
  containers:
  - name: cwa-test-controller-container
    image: solomonahmed/redis-alpine-git
    command: ["/bin/sh", "-c"] 
    args:
    - "mkdir git \
    && cd git \
    && git clone --no-checkout --depth 1 https://github.com/ministryofjustice/laa-cwa-feature-tests . \
    && git ls-tree --name-status -r HEAD features | grep \".feature\" | awk '{print \"LPUSH ft \" $1}' > features.txt \
    && redis-cli -h cwa-test-redis-service < features.txt \
    && cat features.txt"
  initContainers:
  - name: check-redis-service
    image: busybox
    command: ["/bin/sh", "-c"] 
    args: 
    - 'until nslookup cwa-test-redis-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for cwa-test-redis-service; sleep 2; done'
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: cwa-test-redis-service #service uses the Domain Name cwa-test-redis-service
spec:
  ports:
    - port: 6379 #The port this service will be available on
      targetPort: 6379 #The container port the service will forward to
  #All pods with the app=cwa-test-redis label will be part of this service.
  selector:
    app: cwa-test-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwa-test-redis-deployment
  labels:
    app: cwa-test-redis
spec:
  selector:
    matchLabels:
      app: cwa-test-redis
  template:
    metadata:
      labels:
        app: cwa-test-redis
    spec:
      containers:
      - name: cwa-test-redis-container
        image: redis:7.2.4-alpine
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cwa-ft-test-job
spec:
  parallelism: 3
  template:
    metadata:
      name: cwa-test-runner-container
    spec:
      containers:
      - name: cwa-test-runner-container
        image: docker.io/library/laa-cwa-feature-tests-ch:latest
        imagePullPolicy: Never
        env:
        - name: TEST_ENV
          value: dev
        - name: REDIS_SERVICE_HOST
          value: cwa-test-redis-service
        - name: CWA_TEST_PROVIDER_API
          value: http://cwa-test-provider-api:8080
        - name: FT_API
          value: "true"
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-redis
        image: busybox:latest
        command: ['sh', '-c', 'until nc -vz cwa-test-redis-service 6379; do echo "Waiting for redis..."; sleep 1; done;']
      - name: wait-for-api
        image: busybox:latest
        command: ['sh', '-c', 'until nc -vz cwa-test-provider-api 8080; do echo "Waiting for cwa-test-provider-api..."; sleep 1; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: cwa-test-provider-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cwa-test-provider-api #target all pods with this label
  #for local dev testing so we can access api from localhost:8080
  type: LoadBalancer      # This Service is available for external traffic.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwa-test-provider-deployment
  labels:
    app: cwa-test-provider-api
spec:
  selector:
    matchLabels:
      app: cwa-test-provider-api
  template:
    metadata:
      labels:
        app: cwa-test-provider-api
    spec:
      containers:
      - name: cwa-test-provider-api-container
        image: solomonahmed/cwa-test-provider-api:latest
        #if using local repository use...
        #image: docker.io/library/cwa-test-provider-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: CWA_USER
          valueFrom:
            secretKeyRef:
              name: db-username
              key: db-username
        - name: CWA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: db-password
        - name: CWA_DSN
          valueFrom:
            secretKeyRef:
              name: db-dsn
              key: db-dsn
