apiVersion: batch/v1
kind: Job
metadata:
  name: cwa-ft-test-job
spec:
  parallelism: 3
  template:
    metadata:
      name: cwa-test-runner-container
    spec:
      containers:
      - name: cwa-test-runner-container
        image: solomonahmed/ft-chrome:v0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "256m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false    # The context settings block
          capabilities:                      # the process from escalating to
            drop:                            # higher privileges and drops
              - ALL                          # all additional capabilities.
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        imagePullPolicy: Always
        env:
        - name: TEST_ENV
          value: dev
        - name: REDIS_SERVICE_HOST
          value: cwa-test-redis-service
        - name: CWA_TEST_PROVIDER_API
          value: http://cwa-test-provider-api:8081
        - name: FT_API
          value: "true"
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      initContainers:
      - name: wait-for-redis
        image: solomonahmed/busybox:v0.1
        resources:
          requests:
            memory: "32Mi"
            cpu: "32m"
          limits:
            memory: "64Mi"
            cpu: "64m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false    # The context settings block
          capabilities:                      # the process from escalating to
            drop:                            # higher privileges and drops
              - ALL                          # all additional capabilities.
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        command: ['sh', '-c', 'until nc -vz cwa-test-redis-service 6379; do echo "Waiting for redis..."; sleep 1; done;']
      - name: wait-for-api
        image: solomonahmed/busybox:v0.1
        resources:
          requests:
            memory: "32Mi"
            cpu: "32m"
          limits:
            memory: "64Mi"
            cpu: "64m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false    # The context settings block
          capabilities:                      # the process from escalating to
            drop:                            # higher privileges and drops
              - ALL                          # all additional capabilities.
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        command: ['sh', '-c', 'until nc -vz cwa-test-provider-api 8081; do echo "Waiting for cwa-test-provider-api..."; sleep 1; done;']