name: Helm Deploy
description: Deploy a Helm Chart to Kubernetes

inputs:
  k8s_namespace:
    required: true
    description: "Kubernetes Namespace"
  helm_release_name:
    required: true
    description: "Helm Release Name"
  helm_chart:
    required: true
    description: "Helm Chart"
  helm_values_path:
    required: true
    description: "Path To Helm Values"
  #--Combine the 3 values below for a full image URI if needed
  image_registry:
    required: true
    description: "Image Registry URL"
  image_repo:
    required: true
    description: "Image Repository Path"
  image_tag:
    required: true
    description: "Image Tag"

runs:
  using: "composite"

  steps:
  - name: Helm Deploy
    run: |
      helm install ${{ helm_release_name }} ${{ helm_chart }} \
        -f ${{ helm_values_path }} \
        ${{ helm_additional_options }}
        --set ecr.image.registryAddress=${{ inputs.image_registry }} \
        --set ecr.image.regPath=${{ inputs.image_repo }} \
        --set ecr.image.tag=${{ inputs.image_tag }} \
        --wait --timeout 300s \
        --atomic
    shell: bash
