{{- define "cwa-tests.run.feature-test-runner" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-laa-pcuam-cwa-tests-job
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}
spec:
  completions: 5  # Number of pods to run in parallel
  parallelism: 5  # Number of pods to run at the same time
  template:
    metadata:
      labels:
        app: laa-pcuam-cwa-tests
    spec:
      containers:
      - name: laa-pcuam-cwa-tests
        image: "{{ .Values.global.registryAddress }}/{{ .Values.global.regPath }}:{{ .Values.ecr.image.tag }}"
        env:
        - name: REDIS_SERVICE
          value: "redis://{{ .Release.Name }}-redis-service:6379"
        - name: WORK_Q
          value: "features_list"
        - name: TEST_ENV
          value: {{ .Values.global.test_env }}
        resources:
          requests:
            cpu: 1500m
            memory: 8192Mi
          limits:
            cpu: 4000m
            memory: 8192Mi
        command: ["ruby", "runner.rb"]
      restartPolicy: Never
      serviceAccountName: {{ .Values.global.serviceAccount }}
{{- end -}}