{{- define "cwa-tests.run.feature-test-runner" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-ft-runner-job
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}
spec:
  completions: 20  # Number of pods to run in parallel
  parallelism: 20  # Number of pods to run at the same time
  template:
    metadata:
      labels:
        app: ft-runner-job
    spec:
      containers:
      - name: ft-runner-job
        image: "{{ .Values.global.registryAddress }}/{{ .Values.global.regPath }}:{{ .Values.ecr.image.tag }}"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: "{{ .Values.securityContext.seccompProfile.type }}"
        env:
        - name: REDIS_SERVICE
          value: "redis://{{ .Release.Name }}-redis-service.{{ .Values.global.namespace }}.svc.cluster.local:6379"
        - name: WORK_Q
          value: "features_list"
        - name: TEST_ENV
          value: {{ .Values.global.test_env }}
        resources:
          requests:
            cpu: 1500m
            memory: 8192Mi
          limits:
            cpu: 4000m
            memory: 8192Mi
        command: ["ruby", "runner.rb"]
      restartPolicy: Never
      serviceAccountName: {{ .Values.global.serviceAccount }}
{{- end -}}