{{- define "cwa-tests.run.screenshots-pvc" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-screenshots-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    meta.helm.sh/release-name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
{{- end -}}