{{- define "cwa-tests.setup.redis-service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-service
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
{{- end -}}