{{- define "cwa-tests.setup.s3-setup" -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-s3-setup
  labels:
    app: s3-setup
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}
spec:
  restartPolicy: Never
  serviceAccountName: {{ .Values.global.serviceAccount }}
  securityContext:
    runAsUser: {{ .Values.securityContext.runAsUser }}
    runAsGroup: {{ .Values.securityContext.runAsGroup }}
    fsGroup: {{ .Values.securityContext.fsGroup }}
  containers:
  - name: aws-cli
    image: amazon/aws-cli:2.15.0
    command: ["/bin/sh", "-c"]
    args:
      - |
        mkdir -p /tmp/.aws
        aws s3api put-object --bucket "$S3_BUCKET_NAME" --key "feature-test-runs/$RELEASE_NAME/artefacts/"
        aws s3api put-object --bucket "$S3_BUCKET_NAME" --key "feature-test-runs/$RELEASE_NAME/summary/"
    env:
    - name: HOME
      value: "/tmp"
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: s3-bucket-output
          key: bucket_name
    - name: RELEASE_NAME
      value: {{ .Release.Name }}
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: "{{ .Values.securityContext.seccompProfile.type }}"
{{- end -}}