name: Build and Push Image

on:
  workflow_call:
    inputs:
      k8s_namespace:
        required: true
        type: string
      helm_release_name:
        required: true
        type: string
      helm_chart:
        required: true
        type: string
      helm_values_path:
        required: true
        type: string
      #--Combine the 3 values below for a full image URI if needed
      image_registry:
        required: true
        type: string
      image_repo:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  helm_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #--v4.2.2

      #--Auth
      - name: Kube Authentication
        uses: ./.github/workflows/composite-kube-auth
        with:
          k8s_cluster_name: ${{ secrets.KUBE_CLUSTER }}
          k8s_namespace: ${{ inputs.k8s_namespace }}
          kube_token: "${{ secrets.KUBE_TOKEN }}"

      # Helm Deploy
      - run: |
          helm install ${{ helm_release_name }} ${{ helm_chart }} \
            -f ${{ helm_values_path }} \
            ${{ helm_additional_options }}
            --set ecr.image.registryAddress=${{ inputs.image_registry }} \
            --set ecr.image.regPath=${{ inputs.image_repo }} \
            --set ecr.image.tag=${{ inputs.image_tag }} \
            --wait --timeout 300s \
            --atomic
