apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-debug-values
  labels:
    meta.helm.sh/release-name: {{ .Release.Name }}
data:
  redisSetupImageTag: "{{ .Values.redisSetup.image.tag }}"
  circleSha1: "{{ .Values.global.circle_sha1 }}"