apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  securityContext:
    runAsUser: 1000  # Specify a non-root user ID
    runAsGroup: 1000 # Specify a non-root group ID
    fsGroup: 1000    # Ensure file system permissions are correct
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379