apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-redis-setup
  labels:
    app: redis-setup
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Chart.Name }}
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}
spec:
  restartPolicy: Never
  serviceAccountName: {{ .Values.global.serviceAccount }}
  securityContext:
  runAsUser: {{ .Values.securityContext.runAsUser }}
  runAsGroup: {{ .Values.securityContext.runAsGroup }}
  fsGroup: {{ .Values.securityContext.fsGroup }}
  initContainers:
    - name: setup
      image: {{ .Values.global.registryAddress }}/{{ .Values.global.regPath }}:{{ .Values.redisSetup.image.tag }}
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: {{ toYaml .Values.securityContext.capabilities.drop | nindent 10 }}
        seccompProfile:
          type: {{ .Values.securityContext.seccompProfile.type }}
      env:
      - name: COMMIT_SHA
        value: "{{ .Values.global.circle_sha1 }}"
  containers:
    - name: wait-for-redis
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]