apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Chart.Name }}
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      serviceAccountName: {{ .Values.global.serviceAccount }}
      containers:
        - name: redis
          image: {{ .Values.ecr.image.registryAddress }}/{{ .Values.ecr.image.regPath }}:{{ .Values.ecr.image.tag }}
          ports:
            - containerPort: 6379
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: {{ toYaml .Values.securityContext.capabilities.drop | nindent 10 }}
            seccompProfile:
              type: {{ .Values.securityContext.seccompProfile.type }}
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi