name: Configure kubecontext
description: Configure kubecontext for environment specific deployment

inputs:
  k8s_cluster_name:
    required: true
    description: "Kubernetes Cluster Name"
    default: ${{ vars.K8S_CLUSTER_NAME }}
  k8s_namespace:
    required: true
    description: "Kubernetes Namespace"
  kube_token:
    required: true
    description: "Kubernetes API Token"
    default: "${{ vars.K8S_TOKEN }}"

runs:
  using: "composite"

  steps:
  - name: Kubernetes Auth
    run: |
      echo "${{ inputs.cert }}" > ca.crt
      kubectl config set-cluster ${{ inputs.k8s_cluster_name }} --certificate-authority=./ca.crt --server="https://${{ ${{ inputs.k8s_cluster_name }}"
      kubectl config set-credentials cd-serviceaccount --token=${{ inputs.kube_token }}
    shell: bash

  - name: Configure kubecontext
    run: |  
      kubectl config set-context ${{ inputs.k8s_cluster_name }} --cluster=${{ inputs.k8s_cluster_name }} --user=cd-serviceaccount --namespace=${{ inputs.k8s_namespace }}
      kubectl config use-context ${{ inputs.k8s_cluster_name }}
    shell: bash
