Feature: Validate IRC Procurement Area and access point combinations used after disabled date

  Scenario: validate irc procurement area and access pointwhich are end dated for ASYLUM
    Given a test firm user is logged in CWA
    And user prepares to submit outcomes for test provider "LEGAL HELP.IMMAS#13"
    Given the following Matter Types are chosen:
      | IALB:IOUT |
    And the following outcomes are bulkloaded:
      | #  | CASE_ID | UFN        | CLAIM_TYPE | STAGE_REACHED | CASE_START_DATE | PROCUREMENT_AREA | ACCESS_POINT | IRC_SURGERY | EXEMPTION_CRITERIA_SATISFIED |
      |  1 |     101 | 010212/101 | CM         | IE            |      01/02/2012 | PA00142          | AP00000      |             |                              |
      |  2 |     102 | 010212/102 | CM         | IE            |      01/02/2012 | PA00143          | AP00000      |             |                              |
      |  3 |     103 | 010212/103 | CM         | IE            |      01/02/2012 | PA00144          | AP00000      |             |                              |
      |  4 |     104 | 010212/104 | CM         | IE            |      01/02/2012 | PA00145          | AP00000      |             |                              |
      |  5 |     105 | 010212/105 | CM         | IE            |      01/02/2012 | PA00146          | AP00000      |             |                              |
      |  6 |     106 | 010212/106 | CM         | IE            |      01/02/2012 | PA00147          | AP00000      |             |                              |
      |  7 |     107 | 010212/107 | CM         | IE            |      01/02/2012 | PA00148          | AP00000      |             |                              |
      |  8 |     108 | 010212/108 | CM         | IE            |      01/02/2012 | PA00149          | AP00000      |             |                              |
      |  9 |     109 | 010212/109 | CM         | IE            |      01/02/2012 | PA00150          | AP00000      |             |                              |
      | 10 |     110 | 010212/110 | CM         | IE            |      01/02/2012 | PA00177          | AP00000      |             |                              |
      | 11 |     111 | 010918/111 | CM         |               |      01/09/2018 | PA00145          | AP00186      | N           | TR001                        |
      | 12 |     112 | 010918/112 | CM         |               |      01/09/2018 | PA00145          | AP00187      | N           | TR001                        |
      | 13 |     113 | 010918/113 | CM         |               |      01/09/2018 | PA00146          | AP00186      | N           | TR001                        |
      | 14 |     114 | 010918/114 | CM         |               |      01/09/2018 | PA00146          | AP00187      | N           | TR001                        |
      | 15 |     115 | 010918/115 | CM         |               |      01/09/2018 | PA00149          | AP00186      | N           | TR001                        |
      | 16 |     116 | 010918/116 | CM         |               |      01/09/2018 | PA00149          | AP00187      | N           | TR001                        |
    Then user should see the outcome results page
    And problem outcomes should equal 16
    And the following errors:
      | Matter Type / Stage Reached | UFN        | Error Type     | Description                                                                                                                                                                                                                                                                     |
      | IALB:IOUT                   | 010212/101 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/102 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/103 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/104 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/105 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/106 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/107 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/108 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/109 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010212/110 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010918/111 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010918/112 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010918/113 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010918/114 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010918/115 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IALB:IOUT                   | 010918/116 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |

  Scenario: validate irc procurement area and access pointwhich are end dated for IMMIGRATION
    Given a test firm user is logged in CWA
    And user prepares to submit outcomes for test provider "LEGAL HELP.IMMOT#13"
    Given the following Matter Types are chosen:
      | IMLB:IOUT |
    And the following outcomes are bulkloaded:
      | #  | CASE_ID | UFN        | CLAIM_TYPE | STAGE_REACHED | CASE_START_DATE | PROCUREMENT_AREA | ACCESS_POINT | IRC_SURGERY | EXEMPTION_CRITERIA_SATISFIED |
      |  1 |     101 | 010212/101 | CM         | IE            |      01/02/2012 | PA00142          | AP00000      |             |                              |
      |  2 |     102 | 010212/102 | CM         | IE            |      01/02/2012 | PA00143          | AP00000      |             |                              |
      |  3 |     103 | 010212/103 | CM         | IE            |      01/02/2012 | PA00144          | AP00000      |             |                              |
      |  4 |     104 | 010212/104 | CM         | IE            |      01/02/2012 | PA00145          | AP00000      |             |                              |
      |  5 |     105 | 010212/105 | CM         | IE            |      01/02/2012 | PA00146          | AP00000      |             |                              |
      |  6 |     106 | 010212/106 | CM         | IE            |      01/02/2012 | PA00147          | AP00000      |             |                              |
      |  7 |     107 | 010212/107 | CM         | IE            |      01/02/2012 | PA00148          | AP00000      |             |                              |
      |  8 |     108 | 010212/108 | CM         | IE            |      01/02/2012 | PA00149          | AP00000      |             |                              |
      |  9 |     109 | 010212/109 | CM         | IE            |      01/02/2012 | PA00150          | AP00000      |             |                              |
      | 10 |     110 | 010212/110 | CM         | IE            |      01/02/2012 | PA00177          | AP00000      |             |                              |
      | 11 |     111 | 010413/111 | CM         |               |      01/04/2013 | PA00177          | AP00186      | N           | TR001                        |
      | 12 |     112 | 010413/112 | CM         |               |      01/04/2013 | PA00142          | AP00186      | N           | TR001                        |
      | 13 |     113 | 010413/113 | CM         |               |      01/04/2013 | PA00143          | AP00186      | N           | TR001                        |
      | 14 |     114 | 010413/114 | CM         |               |      01/04/2013 | PA00144          | AP00186      | N           | TR001                        |
      | 15 |     115 | 010413/115 | CM         |               |      01/04/2013 | PA00145          | AP00186      | N           | TR001                        |
      | 16 |     116 | 010413/116 | CM         |               |      01/04/2013 | PA00146          | AP00186      | N           | TR001                        |
      | 17 |     117 | 010413/117 | CM         |               |      01/04/2013 | PA00147          | AP00186      | N           | TR001                        |
      | 18 |     118 | 010413/118 | CM         |               |      01/04/2013 | PA00148          | AP00186      | N           | TR001                        |
      | 19 |     119 | 010413/119 | CM         |               |      01/04/2013 | PA00149          | AP00186      | N           | TR001                        |
      | 20 |     120 | 010413/120 | CM         |               |      01/04/2013 | PA00150          | AP00186      | N           | TR001                        |
      | 21 |     121 | 010918/121 | CM         |               |      01/09/2018 | PA00145          | AP00187      | N           | TR001                        |
      | 22 |     122 | 010918/122 | CM         |               |      01/09/2018 | PA00146          | AP00187      | N           | TR001                        |
      | 23 |     123 | 010918/123 | CM         |               |      01/09/2018 | PA00149          | AP00187      | N           | TR001                        |
    Then user should see the outcome results page
    And problem outcomes should equal 23
    And the following errors:
      | Matter Type / Stage Reached | UFN        | Error Type     | Description                                                                                                                                                                                                                                                                     |
      | IMLB:IOUT                   | 010212/101 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/102 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/103 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/104 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/105 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/106 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/107 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/108 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/109 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010212/110 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/111 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/112 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/113 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/114 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/115 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/116 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/117 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/118 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/119 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010413/120 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010918/121 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010918/122 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
      | IMLB:IOUT                   | 010918/123 | Inactive PA/AP | The Category of Law, Procurement Area and Access Point combination that has been used is not valid for the date that has been recorded. This may be because the combination was end dated prior to this date or because the combination had not yet become active at this date. |
