name: Build and Push Image
description: Build Image and Push to Container Registry

inputs:
  image_registry:
    required: true
    description: "Image Registry URL"
  image_repository:
    required: true
    description: "Image Repository URL"
  build_path:
    required: true
    description: "Docker Build Path"
    default: "."

outputs:
  image_registry:
    description: "Image Registry URL"
    value: ${{ env.REGISTRY }}
  image_repo:
    description: "Image Repo Path"
    value: ${{ env.REPOSITORY }}
  image_tag:
    description: "Image Tag"
    value: ${{ env.IMAGE_TAG }}

runs:
  using: "composite"

  steps:
  - name: Docker Build
    run: |
        docker build ${{ inputs.build_path }} -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    shell: bash
    env:
      REGISTRY: ${{ inputs.image_registry }}
      REPOSITORY: ${{ inputs.image_repository }}
      IMAGE_TAG: ${{ github.sha }}
