name: Build and Push Image
description: Build Image and Push to Container Registry

inputs:
  image_registry:
    required: true
    description: "Image Registry URL"
  image_repository:
    required: true
    description: "Image Repository URL"
  dockerfile_path:
    required: true
    description: "Dockerfile Path"
    default: "Dockerfile"
  image_tag:
    description: "Image Tag"
    default: ${{ github.sha }}

outputs:
  image_registry:
    description: "Image Registry URL"
    value: ${{ env.REGISTRY }}
  image_repo:
    description: "Image Repo Path"
    value: ${{ env.REPOSITORY }}
  image_tag:
    description: "Image Tag"
    value: ${{ env.IMAGE_TAG }}

runs:
  using: "composite"

  steps:
  - name: Docker Build
    run: |
        docker build . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ${{ inputs.dockerfile_path }}
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo image_registry=$REGISTRY >> "$GITHUB_OUTPUT"
        echo image_repo=$REPOSITORY >> "$GITHUB_OUTPUT"
        echo image_tag=$IMAGE_TAG >> "$GITHUB_OUTPUT"
    shell: bash
    env:
      #--These vars might seem to be making things more complicated, but can be useful
      #--when working in container systems as they are usually respected over anything else
      REGISTRY: ${{ inputs.image_registry }}
      REPOSITORY: ${{ inputs.image_repository }}
      IMAGE_TAG: ${{ inputs.image_tag }}
