on:
  push:

jobs:
  dev_build_and_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    uses: ./.github/workflows/_reusable-build-and-push.yml
    with:
      deployment_environment: dev
