on:
  push:

jobs:
  cp_dev_workflow:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/cp-build-and-deploy.yml@feat/add-cp-functions
    with:
      helm_release_name: laa-cwa-feature-tests-${GITHUB_SHA::7}
      helm_chart: ./charts/cwa-tests
      helm_values_path: charts/cwa-tests/Values.yaml
      helm_additional_args: --set run=true --set global.registryAddress=${{ secrets.ECR_REGISTRY_URL }} --set global.regPath=${{ inputs.vars.ECR_REPOSITORY }} --set ecr.image.tag=${{ github.sha }}
    secrets: inherit

  tail_and_purge:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #--v4.2.2

      - name: Kube Auth
        id: auth
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/authenticate_to_cluster@feat/add-cp-functions
        with:
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          kube-sa: cd-serviceaccount
          kube-token: "${{ secrets.KUBE_TOKEN }}"
          kube-cert: ${{ secrets.KUBE_CERT }}

      - name: Show Test Logs
        id: logs
        run: |
          export POD_NAME=$(kubectl get pods -n ${{ secrets.KUBE_NAMESPACE }} --no-headers | awk '{print $1}' | grep '^cwa-tests-[0-9]\{10\}$' | sort | tail -1)
          kubectl logs -f -n ${{ secrets.KUBE_NAMESPACE }} $POD_NAME

      - name: Purge Deployments
        id: purge
        run: |
          helm ls -n ${{ secrets.KUBE_NAMESPACE }} --short | xargs -L1 -I {} helm uninstall {} -n ${{ secrets.KUBE_NAMESPACE }}
