on:
  push:

jobs:
  debug:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo ${{ secrets.KUBE_CERT }}

  build_and_push:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #--v4.2.2

      - name: ECR Auth
        id: auth
        uses: ./.github/actions/ecr-auth
        with:
          ecr_region: ${{ vars.ECR_REGION }}
          ecr_role: ${{ secrets.ECR_ROLE_TO_ASSUME }}

      - name: Build and Push Redis
        id: build_redis
        uses: ./.github/actions/build-and-push
        with:
          image_registry: ${{ steps.auth.outputs.image_registry }}
          image_repository: ${{ vars.ECR_REPOSITORY }}
          dockerfile_path: ./docker/Dockerfile
          image_tag: "redis-${{ github.sha }}"

      - name: Build and Push Tests
        id: build_tests
        uses: ./.github/actions/build-and-push
        with:
          image_registry: ${{ steps.auth.outputs.image_registry }}
          image_repository: ${{ vars.ECR_REPOSITORY }}

    outputs:
      image_registry: ${{ steps.build_tests.outputs.image_registry }}
      image_repo: ${{ steps.build_tests.outputs.image_repo }}
      image_tag_redis: ${{ steps.build_redis.outputs.image_tag }}
      image_tag_tests: ${{ steps.build_tests.outputs.image_tag }}

  helm_deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build_and_push
    environment: dev
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #--v4.2.2

      - name: Kube Authentication
        id: auth
        uses: ./.github/actions/kube-auth
        with:
          k8s_cluster_name: ${{ secrets.KUBE_CLUSTER }}
          k8s_namespace: ${{ secrets.KUBE_NAMESPACE }}
          k8s_service_account: cd-serviceaccount
          k8s_token: "${{ secrets.KUBE_TOKEN }}"
          k8s_cert: ${{ secrets.KUBE_CERT }}

      - name: Helm Deploy
        id: task
        uses: ./.github/actions/helm-deploy
        with:
          k8s_cluster_name: ${{ secrets.KUBE_CLUSTER }}
          k8s_namespace: ${{ vars.K8S_NAMESPACE }}
          helm_release_name: laa-cwa-feature-tests-${GITHUB_SHA::7}
          helm_chart: ./charts/cwa-tests
          helm_values_path: charts/cwa-tests/Values.yaml
          image_registry: ${{needs.build_and_push.outputs.image_registry}}
          image_repo: ${{needs.build_and_push.outputs.image_repo}}
          image_tag: ${{needs.build_and_push.outputs.image_tag_tests}}

      - name: Show Test Logs
        id: logs
        run: |
          export POD_NAME=$(kubectl get pods -n ${{ secrets.KUBE_NAMESPACE }} --no-headers | awk '{print $1}' | grep '^cwa-tests-[0-9]\{10\}$' | sort | tail -1)
          kubectl logs -f -n ${{ secrets.KUBE_NAMESPACE }} $POD_NAME

      - name: Purge Deployments
        id: purge
        run: |
          helm ls -n ${{ secrets.KUBE_NAMESPACE }} --short | xargs -L1 -I {} helm uninstall {} -n ${{ secrets.KUBE_NAMESPACE }}
